# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The issues are also
# reported to the command line by the `flutter analyze` command.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a entire class by annotating the code with the 'suppress' comment.
  # The name of the variable used within the annotation must match the name
  # of the lint.
  #
  # In addition to the lints provided by package:flutter_lints/flutter.yaml,
  # the lint rules below are also applied.
  rules:
    - camel_case_extensions
    - camel_case_types
    - empty_catches
    - empty_statements
    - avoid_function_literals_in_foreach_calls
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_string_interpolations
    - unnecessary_to_list_in_spreads

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
